version: "3.9"

services:
  douyin_tiktok_download_api:
    image: evil0ctal/douyin_tiktok_download_api
    container_name: douyin_tiktok_download_api
    restart: always
    volumes:
      - ./path/config.yaml:/crawlers/douyin/web/config.yaml
      - ./path/config.yaml:/crawlers/tiktok/web/config.yaml
      - ./path/config.yaml:/crawlers/tiktok/app/config.yaml
    environment:
      TZ: Asia/Shanghai
      PUID: 1026
      PGID: 100
    ports:
      - 80:80
    privileged: true
    deploy:
      resources:
        limits:
          cpus: '0.80'
