version: "3.9"

services:

  # bot
  douyin_tiktok_download_api:
    image: evil0ctal/douyin_tiktok_download_api
    network_mode: host
    container_name: douyin_tiktok_download_api
    restart: always
    volumes:
      - ./config.yml:/app/config.yml
    environment:
      TZ: Asia/Shanghai
    deploy:
      resources:
        limits:
          cpus: '0.80'
