# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install pipenv
      run: pipx install pipenv
    - uses: actions/setup-python@v2.3.1
      with:
        python-version: '3.9.9'
        cache: 'pipenv'
        cache-dependency-path: |
          server/app/Pipfile.lock
          __test__/app/Pipfile.lock
    - run: pipenv install
    - run: sudo pip install -r requirements.txt
    - run: sudo python TikTok_ZH.py
